### ISSUE TITLE
FFplay: Videos don't 'fit to screen' when the resolution is bigger than the monitor

### ISSUE THREAD

**Issue by tonyo101** [ps5-payload-dev/websrv#3]

**Comment by tonyo101** [comment]
The video will play zoomed in if the resolution of the video is higher than the resolution of the monitor (for example, a 1080p monitor playing a 4K video).

This can be fixed by launching ffplay with `-fs`.

**Comment by john-tornblom** [comment]
Ah, thanks for the fix, commit with 01639ea86dcee571b08f212239a5c6c2d709b548

**Comment by tonyo101** [comment]
Could we also get a fix for locally stored files in `/data/hombrew/FFplay/media`?

Thank you!

**Comment by john-tornblom** [comment]
Please open up a new issue where you describe the problem (I do not understand what the issue is), and I'll have a look.

**Comment by tonyo101** [comment]
Do I have to? It's the same issue. If I play a 4K video on my 1080p monitor, it's "zoomed in."

I'm looking for a fix here:
https://github.com/ps5-payload-dev/websrv/blob/master/homebrew/FFplay/homebrew.js

**Comment by john-tornblom** [comment]
Ah, I did not understand the issue, but now I do, fixed in 975326a1d2013ebbfe3a228b953f4b48b31e510f

**Comment by tonyo101** [comment]
Thank you. I love all the work you're doing for the PS5. :heart:
