### ISSUE TITLE
Question: Would it be possible to port MPV or VLC to the PS5?

### ISSUE THREAD

**Issue by tonyo101** [ps5-payload-dev/websrv#4]
The lack of support for SRT subtitles in FFplay is kind of a deal breaker for me. :disappointed:

**Comment by john-tornblom** [comment]
Possible, yes, but need precompiled opengl shaders in SDL first. This is out of scope of websrv.

**Comment by tonyo101** [comment]
Please think about adding support for text-based subtitles (it doesn't have to be with MPV or VLC). There's gotta be a way!

**Comment by tonyo101** [comment]
How we doing on the softsub situation?
