### ISSUE TITLE
FBNeo D-pad problem

### ISSUE THREAD

**Issue by ChatKnight** [ps5-payload-dev/websrv#8]
hi, i think there's a problem with FBNeo remapping .INI file for specific game

i noticed each time i reassign the PS5 D-Pad instead of the left joystick on any game it work but if i press any button like the fire button or the jump button for example then the character stop moving and the d-pad doesnt work anymore until i release the jump button and press the d-pad again i know that my controller is working perfectly fine with everthing else so it's not an issue with the controller 

this is when i create a cyberlip.ini on my pc and i add it in
/data/homebrew/FBNeo/config/games
but in
/user/home/xxxxxxxxx/FBNeo/config/games
it doesnt work at all

and if i try to press tab on the keyboard and change the input from the game setting menu itself it always add the input on joystick 1 even if in game my controller is recognized as joystick 0 and also even if i try to save the config its doesnt create a .ini file in folder

/data/homebrew/FBNeo/config/games
or
/user/home/xxxxxxxxx/FBNeo/config/games

can you help please ?

**Comment by john-tornblom** [comment]
I am not super familiar with FBNeo, sorry. I did change so the used config is printed to stdout in the most recent build though
